{% set name = "sos-rmarkdown" %}
{% set version = "0.1.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 45e943e4b6a987f594763bccd8232c109580c0142e3fc801e5ed3e187831889b

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - sos-notebook
    - sos-r
    - markdown-kernel
    - papermill
    - sos-papermill
    - nbformat

test:
  requires:
    - python {{ python_min }}
  imports:
    - sos_rmarkdown

about:
  home: https://github.com/vatlab/sos-rmarkdown
  license: BSD-3-Clause
  license_file: LICENSE
  summary: "A converter from Rmarkdown to SoS Notebook"
  doc_url: https://github.com/vatlab/sos-rmarkdown
  dev_url: https://github.com/vatlab/sos-rmarkdown

extra:
  recipe-maintainers:
    - BoPeng
