{% set name = "sos-rmarkdown" %}
{% set version = "0.1.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d2c2b7ef3c7a9e14803bfce363e38a82d77f525462388a6733f367116d2e0cb0

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - sos-notebook
    - sos-r
    - markdown-kernel
    - papermill
    - sos-papermill
    - nbformat

test:
  imports:
    - sos_rmarkdown

about:
  home: https://github.com/vatlab/sos-rmarkdown
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "A converter from Rmarkdown to SoS Notebook"
  doc_url: https://github.com/vatlab/sos-rmarkdown
  dev_url: https://github.com/vatlab/sos-rmarkdown

extra:
  recipe-maintainers:
    - BoPeng
