schema_version: 1

context:
  version: "0.1.6"

package:
  name: sos-rmarkdown
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/sos-rmarkdown/sos_rmarkdown-${{ version }}.tar.gz
  sha256: 186f492f577b5a197c2388452df7fa7136aea0b979d4d3fd7572d1b48b6b2f40

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python =${{ python_min }}
    - setuptools
  run:
    - python >=${{ python_min }}
    - sos-notebook
    - sos-r
    - markdown-kernel
    - papermill
    - sos-papermill
    - nbformat

tests:
  - python:
      imports:
        - sos_rmarkdown
  - requirements:
      run:
        - pip
        - python =${{ python_min }}
    script:
      - pip check

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A converter from Rmarkdown to SoS Notebook
  homepage: https://github.com/vatlab/sos-rmarkdown
  repository: https://github.com/vatlab/sos-rmarkdown
  documentation: https://github.com/vatlab/sos-rmarkdown

extra:
  recipe-maintainers:
    - danielnachun
    - BoPeng
